[#122][Flashcards/JavaScript] Avoid an idempotent log error message.
It doesn't have any impact, besides a harmless error message:
```
TypeError: Cannot read properties of null (reading 'split')
```
Still, it's cleaner to avoid it.